version: "3.7"

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx
    ports:
      - 80:80
    depends_on:
      - web

    # 1. Set nginx microservice
    # 2. Set restart policy -> always
    # 3. Link conf.d local folder with /etc/nginx
    # 4. Expose ports
    # 5. Run this microservice after setting up server and web services (depends_on)
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: tasks
    volumes:
      - db_data:/data/db

    # 1. Set mongo microservice
    # 2. Set MONGO_INITDB_DATABASE -> tasks
    # 3. Expose mongo ports
    # 4. Link created volume with /data/db folder
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./server/src:/app/src
    ports:
      - 5000:5000
    environment:
      DB_URL: db
      DB_PORT: 27016

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000

volumes:
  db_data:

